services:
  odoo-nginx:
    image: odoo-nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: odoo-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  odoo:
    image: ev-odoo-baisc:latest
    build:
      context: ./odoo
      dockerfile: Dockerfile
    command: ["-c", "./run-profiles/cloud-ubuntu/env.conf", "-i", "ev-accounting-basic", "--without-demo", "all"]
    restart: always
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    volumes:
      - "../../data/odoo:/var/lib/odoo"
      - "../../license:/ev-odoo/license"

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ev-odoo-basic
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - "../../data/db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"